name: smart_garden_app
description: "A Smart Garden project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  hive: ^2.2.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.1
  json_serializable: ^6.9.5
  custom_lint: ^0.7.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
          - asset: assets/fonts/Montserrat-Thin.ttf
          - asset: assets/fonts/Montserrat-ExtraLight.ttf
          - asset: assets/fonts/Montserrat-Light.ttf
          - asset: assets/fonts/Montserrat-Regular.ttf
          - asset: assets/fonts/Montserrat-Medium.ttf
          - asset: assets/fonts/Montserrat-SemiBold.ttf
          - asset: assets/fonts/Montserrat-Bold.ttf
          - asset: assets/fonts/Montserrat-ExtraBold.ttf
          - asset: assets/fonts/Montserrat-Black.ttf
          - asset: assets/fonts/Montserrat-ThinItalic.ttf
          - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          - asset: assets/fonts/Montserrat-LightItalic.ttf
          - asset: assets/fonts/Montserrat-Italic.ttf
          - asset: assets/fonts/Montserrat-MediumItalic.ttf
          - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          - asset: assets/fonts/Montserrat-BoldItalic.ttf
          - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          - asset: assets/fonts/Montserrat-BlackItalic.ttf